default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: "macbook"
  host: localhost

development:
  <<: *default
  database: personal_finance_tracker_development
